# Generated by Django 3.0.5 on 2020-12-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CartApp', '0004_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
